"""initial schema

Revision ID: 411e5211381c
Revises: 
Create Date: 2026-09-16 14:10:06.613534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '411e5211381c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_timestamp'))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('encrypted_aes_key',
               existing_type=sa.VARBINARY(length=512),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_files_mahasiswa'))
        batch_op.create_index(batch_op.f('ix_files_mahasiswa_id'), ['mahasiswa_id'], unique=False)

    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.alter_column('uts_enc',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.alter_column('uas_enc',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.alter_column('tugas_enc',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.alter_column('praktikum_enc',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_nilai_mahasiswa'))
        batch_op.create_index(batch_op.f('ix_nilai_mahasiswa_id'), ['mahasiswa_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('mahasiswa', 'dosen', 'admin'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'mahasiswa'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('mahasiswa', 'dosen', 'admin'),
               existing_nullable=False,
               existing_server_default=sa.text("'mahasiswa'"))

    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nilai_mahasiswa_id'))
        batch_op.create_index(batch_op.f('idx_nilai_mahasiswa'), ['mahasiswa_id'], unique=False)
        batch_op.alter_column('praktikum_enc',
               existing_type=sa.LargeBinary(),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)
        batch_op.alter_column('tugas_enc',
               existing_type=sa.LargeBinary(),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)
        batch_op.alter_column('uas_enc',
               existing_type=sa.LargeBinary(),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)
        batch_op.alter_column('uts_enc',
               existing_type=sa.LargeBinary(),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_mahasiswa_id'))
        batch_op.create_index(batch_op.f('idx_files_mahasiswa'), ['mahasiswa_id'], unique=False)
        batch_op.alter_column('encrypted_aes_key',
               existing_type=sa.LargeBinary(),
               type_=sa.VARBINARY(length=512),
               existing_nullable=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###
